backend:
  name: git-gateway
  branch: master

locale: 'ja'
media_folder: static/img
public_folder: /img

collections:
  - name: 'blog'
    identifier_field: slug
    label: 'ブログ'
    format: 'json'
    folder: 'assets/content/blog'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'タイトル', name: 'title', widget: 'string' }
      - { label: '説明', name: 'description', widget: 'string' }
      - { label: 'スラッグ', name: 'slug', widget: 'string' }
      - { label: '作成日', name: 'createDate', widget: 'datetime', format: 'YYYY-MM-DD HH:mm:ss' }
      - { label: '更新日', name: 'updateDate', widget: 'datetime', format: 'YYYY-MM-DD HH:mm:ss' }
      - { label: '本文', name: 'body', widget: 'markdown' }